import Head from 'next/head'
import React, { useState } from 'react'
import { client } from '../../../SanityClient'

import imageUrlBuilder from '@sanity/image-url'

import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Navigation, Thumbs } from "swiper";
// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import { useBearStore } from '../../../zustand/Store';
import SizeList from '@/components/products/SizeList';

//React Toastify
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

function index({product}) {
  const cart = useBearStore((state)=>state.cart.items)
  const addItemToCart = useBearStore((state)=>state.addItemToCart)
  const addItemToWishList = useBearStore((state)=>state.addItemToWishList)

 
    //Slideshow States
  const [thumbsSwiper, setThumbsSwiper] = useState(null);

  const builder = imageUrlBuilder(client)
    function urlFor(source){
        return builder.image(source)
    }

    const newItemToBeAdded = {
        id:product.slug.current,
        name:product.name,
        price:product.price,
        qtyInCart:product.qtyInCart,
        totalAmount:product.totalAmount,
        brand:product.brand
      }
    
    function addToCart (){
        addItemToCart(newItemToBeAdded)
        toast.success(`${product.name} was added to your cart.`, {
          position: "top-center",
          autoClose: 3000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
          });
    }
    function addToWishList (){
        addItemToWishList(newItemToBeAdded)
        toast.success(`${product.name} was added to your Wishlist.`, {
          position: "top-center",
          autoClose: 3000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
          });
    }

    const formattedPrice = new Intl.NumberFormat('en-US', {style: 'currency', currency: 'USD'}).format(product.price);

  return (
    <>
        <Head>
            <title>{product.name}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='pt-[12vh] text-clash'>
            <section className='w-full p-5'>
                <section className='flex flex-col lg:flex-row justify-between items-center gap-5'>
                    <section className='w-full lg:w-[40%] p-3 grid grid-cols-2 gap-2'>
                      {product.image.map((item)=>{
                        return(
                          <img key={item._key} src={urlFor(item.asset).width(300).url()} alt={`shirt`} className=' mx-auto border border-black'/>
                        )
                      })}
                    </section>
                    <section className='container lg:w-[55%]'>
                        <div className='flex justify-between font-semibold lg:text-2xl'>
                          <section>
                            <p>{product.name}</p>
                            <p className='font-light lg:text-xl'>{product.category}, {product.gender}</p>
                          </section>
                            <p>{formattedPrice}</p>
                        </div>

                        <hr className='my-3 border-black' />
                        <p>{product.details}</p>

                        <section>
                            <p className='font-semibold lg:text-2xl uppercase'>sizes:</p>
                            <SizeList/>
                        </section>

                       <section className='w-full flex justify-between items-center gap-5'>
                          <button className='border w-[45%] text-center py-2 uppercase my-3 hover:scale-105 ease duration-500' onClick={addToWishList}>Add To Wishlist</button>
                          <button className='bg-black text-white w-[45%] text-center py-2 uppercase my-3 hover:scale-105 ease duration-500' onClick={addToCart} >Add To Cart</button>
                       </section>
                    </section>
                </section>
            </section>
            <div className="text-clash">
            <ToastContainer/>
            </div>
        </main>
    </>
  )
}

export default index

export async function getStaticPaths(){
    const query = `*[_type == "product"]
    {
      slug{
        current
      }
    }`
    const product = await client.fetch(query)
  
    const paths = product.map((item)=>({
      params:{
        slug:item.slug.current
      }
    }))
  
    return{
      paths,
      fallback:'blocking'
    }
}

export async function  getStaticProps({params:{slug}}){
    const query = `*[_type == "product"  && slug.current == '${slug}'][0]`
    const product = await client.fetch(query)
    return{
      props:{
        product
      }
    }
  }