import Head from 'next/head'
import { client } from '../../SanityClient'

import imageUrlBuilder from '@sanity/image-url'
import ProductCard from '@/components/products/ProductCard'

export default function Home({products}) {
  const builder = imageUrlBuilder(client)
    function urlFor(source){
        return builder.image(source)
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@400,700,500,600,300&display=swap" rel="stylesheet"></link>
      </Head>
      {/* pt-[10vh] places this element below the navbar: */}
      <main className='pt-[10vh] w-full h-full'> 
          <section className='max-w-[1600px] mx-auto p-5'>
                {/* This will be the homepage's content. It's going to be in categories: */}
                <section className='w-full'>
                      <h1 className="text-center text-clash font-semibold text-2xl uppercase">Featured Items:</h1>
                      <br />
                      {/* Content Shows Here */}
                      <section className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5'>
                        { 
                          products.map((item)=>{
                             if(item.isFeatured == true){
                              return(
                                <ProductCard key={item.slug.current}
                                name={item.name}
                                brand={item.brand}
                                price={item.price}
                                img={urlFor(item.cover_image).width(1000).url()}
                                />
                              )
                             }
                          })
                        }
                      </section>
                </section>
                <br />
                {/* Products By Hackett */}
                <section className='w-full'>
                      <h1 className="text-center text-clash font-semibold text-2xl uppercase">Products By Hackett:</h1>
                      <br />
                      {/* Content Shows Here */}
                      <section className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5'>
                        { 
                          products.map((item)=>{
                             if(item.brand == 'Hackett'){
                              return(
                                <ProductCard key={item.slug.current}
                                name={item.name}
                                brand={item.brand}
                                price={item.price}
                                img={urlFor(item.cover_image).width(1000).url()}
                                />
                              )
                             }
                          })
                        }
                      </section>
                </section>
                <br />
                {/* Products By J.Lindeberg */}
                <section className='w-full'>
                      <h1 className="text-center text-clash font-semibold text-2xl uppercase">Products By J. Lindeberg:</h1>
                      <br />
                      {/* Content Shows Here */}
                      <section className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5'>
                        { 
                          products.map((item)=>{
                             if(item.brand == 'J.Lindeberg'){
                              return(
                                <ProductCard key={item.slug.current}
                                name={item.name}
                                brand={item.brand}
                                price={item.price}
                                img={urlFor(item.cover_image).width(1000).url()}
                                />
                              )
                             }
                          })
                        }
                      </section>
                </section>
          </section>
      </main>
    </>
  )
}


export async function  getStaticProps(){
  const products = await client.fetch(`*[_type == "product"]`)
  return{
    props:{
      products
    }
  }
}