import Head from 'next/head'
import { client } from '../../SanityClient'

import imageUrlBuilder from '@sanity/image-url'
import ProductCard from '@/components/products/ProductCard'

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";

// import required modules
import { Pagination,Autoplay} from "swiper";
import MainSlideShow from '@/components/homepage/MainSlideShow';
import FeaturedItems from '@/components/homepage/FeaturedItems';
import TodaysBrand from '@/components/homepage/TodaysBrand';

export default function Home({products}) {
  const builder = imageUrlBuilder(client)
    function urlFor(source){
        return builder.image(source)
    }
  return (
    <>
      <Head>
        <title>NextCommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* pt-[10vh] places this element below the navbar: */}
      <main className='pt-[10vh] w-full h-full'> 
          <MainSlideShow/>
          <section className='max-w-[1600px] mx-auto p-5'>
                
                <FeaturedItems products={products}/>
                <TodaysBrand products={products}/>
          </section>
      </main>
    </>
  )
}


export async function  getStaticProps(){
  const products = await client.fetch(`*[_type == "product"]`)
  return{
    props:{
      products
    }
  }
}