import Head from 'next/head'
import React, { useState } from 'react'
import { client } from '../../../SanityClient'

import imageUrlBuilder from '@sanity/image-url'
import ProductCard from '@/components/products/ProductCard'

const builder = imageUrlBuilder(client)
    function urlFor(source){
        return builder.image(source)
    }


function index({product}) {
  return(
    <>
        <Head>
            <title>{product[0].brand}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='pt-[12vh] text-clash'>
          <section className='grid grid-cols-3 p-5'>
            {
              product.map((item)=>{
                return(
                  <ProductCard key={item.slug.current}
                  name={item.name}
                  brand={item.brand}
                  price={item.price}
                  slug={`/${item.slug.current}`}
                  img={urlFor(item.cover_image).width(1000).url()}
                  />
                )
              })
            }
          </section>
        </main>
    </>
  )
}

export default index

export async function getStaticPaths(){
    const query = `*[_type == "product"]
    {
      brand
    }`
    const product = await client.fetch(query)
  
    const paths = product.map((item)=>({
      params:{
        brand:item.brand
      }
    }))
  
    return{
      paths,
      fallback:'blocking'
    }
}

export async function  getStaticProps({params:{brand}}){
    const query = `*[_type == "product"  && brand == '${brand}']`
    const product = await client.fetch(query)
    return{
      props:{
        product
      }
    }
  }